"""Pydantic models for API request/response schemas"""
from pydantic import BaseModel
from typing import List, Optional, Dict, Any


class AgentInsight(BaseModel):
    """Insight generated by an AI agent"""
    agent_name: str
    title: str
    message: str
    action: str
    category: str
    priority: str
    confidence: float
    reasoning: str
    data: Optional[Dict[str, Any]] = None


class AnalysisRequest(BaseModel):
    """Request for AI agent analysis"""
    user_data: Dict[str, Any]
    calendar_events: List[Dict[str, Any]]
    location_data: List[Dict[str, Any]]
    current_context: Dict[str, Any]
    manual_scenario: Optional[str] = None


class ScenarioInfo(BaseModel):
    """Information about a detected scenario"""
    type: str
    description: str
    confidence: float
    triggers: List[str]
    context_data: Dict[str, Any] = {}


class AnalysisResponse(BaseModel):
    """Response from AI agent analysis"""
    insights: List[AgentInsight]
    scenario: Dict[str, Any]
    active_agents: int
    total_agents: int
    insights_generated: int
    using_llm: bool
    timestamp: str
