"""Pydantic models for API request/response schemas"""
from pydantic import BaseModel
from typing import List, Optional, Dict, Any


class AgentInsight(BaseModel):
    """Insight generated by an AI agent"""
    agent_name: str
    title: str
    message: str
    action: str
    category: str
    priority: str
    confidence: float
    reasoning: str
    data: Optional[Dict[str, Any]] = None


class AnalysisRequest(BaseModel):
    """Request for AI agent analysis"""
    user_data: Dict[str, Any]
    calendar_events: List[Dict[str, Any]]
    location_data: List[Dict[str, Any]]
    current_context: Dict[str, Any]
    manual_scenario: Optional[str] = None


class ScenarioInfo(BaseModel):
    """Information about a detected scenario"""
    type: str
    description: str
    confidence: float
    triggers: List[str]
    context_data: Dict[str, Any] = {}


class AnalysisResponse(BaseModel):
    """Response from AI agent analysis"""
    insights: List[AgentInsight]
    scenario: Dict[str, Any]
    active_agents: int
    total_agents: int
    insights_generated: int
    using_llm: bool
    timestamp: str


class ConversationMessage(BaseModel):
    """Single message in onboarding conversation"""
    role: str  # 'system' or 'user'
    text: str
    timestamp: str


class VoiceOnboardingRequest(BaseModel):
    """Request for voice onboarding step"""
    conversation_history: List[ConversationMessage]
    current_answer: str


class VoiceOnboardingResponse(BaseModel):
    """Response from voice onboarding step"""
    next_question: str  # Next question to ask, or 'ONBOARDING_COMPLETE'
    analysis: str  # What was learned from user's answer
    preferences_extracted: Dict[str, Any]
    is_complete: bool


class OnboardingPreferences(BaseModel):
    """User preferences collected during onboarding"""
    name: Optional[str] = None
    priorities: List[str] = []  # e.g., ['productivity', 'wellness', 'social']
    work_stress_areas: List[str] = []  # e.g., ['meetings', 'focus', 'deadlines']
    health_goals: List[str] = []  # e.g., ['sleep', 'exercise', 'stress']
    social_preferences: Dict[str, Any] = {}
    financial_goals: List[str] = []
    communication_style: str = "balanced"  # 'brief', 'detailed', 'balanced'
    agent_weights: Dict[str, float] = {}  # Agent priority weights
    raw_conversation: List[ConversationMessage] = []


class OnboardingStatus(BaseModel):
    """Status of user's onboarding"""
    completed: bool
    preferences: Optional[OnboardingPreferences] = None
